<a href="https://colab.research.google.com/github/SOUMOJIT-CHAKRABORTY/Image-Processing/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Tue Sep 27 16:44:31 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


print(torch.__version__)

1.12.1+cu113


#Creating Tensor

Pytorch tensor is created using torch.tensor()

scalar --> lower ,
vector --> lower ,
MATRIX --> UPPER , 
TENSOR --> UPPER.

In [ ]:
# Scalar
scalar = torch.tensor(8)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int

scalar.item()

8

In [ ]:
# Vector
vector = torch.tensor([10,12])
vector

tensor([10, 12])

In [ ]:
vector.ndim

1

In [ ]:
# Size of the vector
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[5,8],[10,4]])
matrix

tensor([[ 5,  8],
        [10,  4]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[0]

tensor([5, 8])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
tensor = torch.tensor([[[3,5,7],[8,5,9],[10,14,13]]])
tensor

tensor([[[ 3,  5,  7],
         [ 8,  5,  9],
         [10, 14, 13]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[ 3,  5,  7],
        [ 8,  5,  9],
        [10, 14, 13]])

### Random Tensors

In [ ]:
# Random Tensor of size of (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6069, 0.0848, 0.0111, 0.9929],
        [0.4934, 0.5849, 0.4757, 0.7869],
        [0.5777, 0.0258, 0.7028, 0.6971]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_tensor_image_size = torch.rand(3,224,224) # image size would be [hight , width , no. of color] ={r , g , b}
random_tensor_image_size 

tensor([[[0.0163, 0.1988, 0.0165,  ..., 0.6296, 0.0727, 0.2136],
         [0.8880, 0.1001, 0.9465,  ..., 0.6870, 0.2533, 0.6304],
         [0.6486, 0.3404, 0.4551,  ..., 0.2316, 0.3728, 0.6635],
         ...,
         [0.5308, 0.1346, 0.2403,  ..., 0.5855, 0.8235, 0.4582],
         [0.5478, 0.0139, 0.3423,  ..., 0.3118, 0.3620, 0.9843],
         [0.9642, 0.8355, 0.5001,  ..., 0.4152, 0.3746, 0.5330]],

        [[0.8346, 0.7045, 0.4033,  ..., 0.9908, 0.9721, 0.8471],
         [0.8852, 0.1214, 0.1789,  ..., 0.5294, 0.3662, 0.9248],
         [0.6078, 0.9255, 0.0024,  ..., 0.4142, 0.4965, 0.8510],
         ...,
         [0.4412, 0.0518, 0.2541,  ..., 0.6628, 0.5670, 0.1240],
         [0.5180, 0.8192, 0.4124,  ..., 0.2317, 0.2668, 0.3705],
         [0.7992, 0.4719, 0.8070,  ..., 0.8990, 0.1084, 0.0827]],

        [[0.2678, 0.3399, 0.0085,  ..., 0.0650, 0.5928, 0.6925],
         [0.0458, 0.6294, 0.8280,  ..., 0.3678, 0.1656, 0.2474],
         [0.3080, 0.0679, 0.4487,  ..., 0.2028, 0.7819, 0.

In [ ]:
random_tensor_image_size.shape , random_tensor_image_size.ndim 

(torch.Size([3, 224, 224]), 3)

## Tensor of zeros and ones


In [ ]:
#creating tensor of zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#creating tensors of ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
zeros*ones
ones.dtype,zeros.dtype

## Creating a range of tensor and tensor-like

In [ ]:
#using torch.arange()
torch.arange(9)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
torch.arange(start=0, end=100, step = 4)

tensor([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68,
        72, 76, 80, 84, 88, 92, 96])

In [ ]:
# creating tensor like
zero_to_ten = torch.arange(start=0, end=10)
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

**Note** Tensor datatypes is one of the three big issues with pytorch and deep learning

1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device



In [ ]:
#float32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32